import "server-only";
import { DatabaseSync, type StatementSync } from "node:sqlite";
import fs from "fs";
import path from "path";
import matter from "gray-matter";

// Defaults to <project root>/data, but this resolves relative to
// process.cwd() at runtime — which for a Next.js `output: standalone`
// deploy is `.next/standalone/`, a folder that gets fully regenerated by
// every new build. If that's how this app is hosted, dashboard-created
// content (posts, enquiries, uploads) would be wiped on every redeploy
// unless DASHBOARD_DATA_DIR is set to a path outside the build output that
// the hosting platform actually keeps between deploys.
const DATA_DIR = process.env.DASHBOARD_DATA_DIR
  ? path.resolve(process.env.DASHBOARD_DATA_DIR)
  : path.join(process.cwd(), "data");
const DB_PATH = path.join(DATA_DIR, "dashboard.db");

let instance: DatabaseSync | null = null;

// Lazy singleton — the connection (and one-time migrations below) only run
// on the first real query, not at module-import time. Next.js's build can
// run dozens of parallel workers that all import every module reachable
// from a page; if this ran at import time, they'd all fight over the same
// SQLite file during static generation and the build would fail with a
// "database locked" error. Pages that read this DB are also marked
// `export const dynamic = "force-dynamic"` so they're never statically
// generated in the first place — this lazy init is the second layer of
// defense, and also what keeps concurrent runtime requests safe.
function getConnection(): DatabaseSync {
  if (instance) return instance;

  if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });
  const conn = new DatabaseSync(DB_PATH);
  conn.exec("PRAGMA busy_timeout = 5000;");
  runMigrations(conn);
  instance = conn;
  return conn;
}

function ensureColumn(conn: DatabaseSync, table: string, column: string, ddl: string) {
  const cols = conn.prepare(`PRAGMA table_info(${table})`).all() as { name: string }[];
  if (!cols.some((c) => c.name === column)) {
    conn.exec(`ALTER TABLE ${table} ADD COLUMN ${ddl}`);
  }
}

function runMigrations(conn: DatabaseSync) {
  conn.exec(`
    CREATE TABLE IF NOT EXISTS blog_posts (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      slug TEXT UNIQUE NOT NULL,
      title TEXT NOT NULL,
      excerpt TEXT NOT NULL,
      image TEXT NOT NULL,
      team TEXT NOT NULL,
      category TEXT NOT NULL,
      date TEXT NOT NULL,
      read_time TEXT NOT NULL,
      tags TEXT NOT NULL,
      author_key TEXT NOT NULL,
      body_markdown TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'published',
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS enquiries (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      created_at TEXT NOT NULL,
      source TEXT NOT NULL,
      name TEXT,
      email TEXT,
      phone TEXT,
      subject TEXT,
      message TEXT,
      data TEXT NOT NULL,
      read INTEGER NOT NULL DEFAULT 0
    );

    CREATE TABLE IF NOT EXISTS job_openings (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      title TEXT NOT NULL,
      department TEXT NOT NULL,
      location TEXT NOT NULL,
      type TEXT NOT NULL,
      description TEXT NOT NULL,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS case_studies (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      ref TEXT UNIQUE NOT NULL,
      cat TEXT NOT NULL,
      pages TEXT NOT NULL,
      title TEXT NOT NULL,
      image TEXT,
      pdf_url TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS resources (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      ref TEXT UNIQUE NOT NULL,
      cat TEXT NOT NULL,
      format TEXT NOT NULL,
      title TEXT NOT NULL,
      image TEXT,
      pdf_url TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    );
  `);

  // Existing databases created before these columns existed won't get them
  // from CREATE TABLE IF NOT EXISTS — add them explicitly, once.
  ensureColumn(conn, "blog_posts", "status", "status TEXT NOT NULL DEFAULT 'published'");
  ensureColumn(conn, "enquiries", "read", "read INTEGER NOT NULL DEFAULT 0");

  // One-time migration: seed the DB from the existing markdown posts the
  // first time this ever runs, so the switchover to DB-backed content
  // doesn't lose the posts that already shipped.
  const postCount = conn.prepare("SELECT COUNT(*) as n FROM blog_posts").get() as { n: number };
  if (postCount.n === 0) {
    const contentDir = path.join(process.cwd(), "content", "insights");
    if (fs.existsSync(contentDir)) {
      const files = fs.readdirSync(contentDir).filter((f) => f.endsWith(".md"));
      const insert = conn.prepare(`
        INSERT INTO blog_posts (slug, title, excerpt, image, team, category, date, read_time, tags, author_key, body_markdown, created_at, updated_at)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `);
      const now = new Date().toISOString();
      for (const file of files) {
        const slug = file.replace(/\.md$/, "");
        const raw = fs.readFileSync(path.join(contentDir, file), "utf8");
        const { data, content } = matter(raw);
        insert.run(
          slug,
          String(data.title ?? ""),
          String(data.excerpt ?? ""),
          String(data.image ?? ""),
          String(data.team ?? ""),
          String(data.category ?? ""),
          String(data.date ?? now.slice(0, 10)),
          String(data.readTime ?? ""),
          JSON.stringify(data.tags ?? []),
          String(data.author ?? "shangeeth"),
          content.trim(),
          now,
          now
        );
      }
    }
  }

  // One-time migration: seed the one job opening that was still hardcoded in
  // the component, so switching Careers to DB-backed data doesn't drop it.
  const jobCount = conn.prepare("SELECT COUNT(*) as n FROM job_openings").get() as { n: number };
  if (jobCount.n === 0) {
    const now = new Date().toISOString();
    conn
      .prepare(
        `INSERT INTO job_openings (title, department, location, type, description, created_at, updated_at)
         VALUES (?, ?, ?, ?, ?, ?, ?)`
      )
      .run(
        "Interior Designer",
        "Design & Interiors",
        "Coimbatore / Remote",
        "Full-time",
        "Develop interior design solutions from concept through construction documentation, working closely with our BIM-integrated workflow.",
        now,
        now
      );
  }

  // One-time migration: seed case studies and resources from their existing
  // markdown content the first time this runs.
  const caseStudyCount = conn.prepare("SELECT COUNT(*) as n FROM case_studies").get() as { n: number };
  if (caseStudyCount.n === 0) {
    const dir = path.join(process.cwd(), "content", "case-studies");
    if (fs.existsSync(dir)) {
      const files = fs.readdirSync(dir).filter((f) => f.endsWith(".md"));
      const insert = conn.prepare(
        `INSERT INTO case_studies (ref, cat, pages, title, image, pdf_url, created_at, updated_at)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?)`
      );
      const now = new Date().toISOString();
      for (const file of files) {
        const raw = fs.readFileSync(path.join(dir, file), "utf8");
        const { data } = matter(raw);
        insert.run(
          String(data.ref ?? ""),
          String(data.cat ?? ""),
          String(data.pages ?? ""),
          String(data.title ?? ""),
          data.image ? String(data.image) : null,
          null,
          now,
          now
        );
      }
    }
  }

  const resourceCount = conn.prepare("SELECT COUNT(*) as n FROM resources").get() as { n: number };
  if (resourceCount.n === 0) {
    const dir = path.join(process.cwd(), "content", "resources");
    if (fs.existsSync(dir)) {
      const files = fs.readdirSync(dir).filter((f) => f.endsWith(".md"));
      const insert = conn.prepare(
        `INSERT INTO resources (ref, cat, format, title, image, pdf_url, created_at, updated_at)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?)`
      );
      const now = new Date().toISOString();
      for (const file of files) {
        const raw = fs.readFileSync(path.join(dir, file), "utf8");
        const { data } = matter(raw);
        insert.run(
          String(data.ref ?? ""),
          String(data.cat ?? ""),
          String(data.format ?? "pdf"),
          String(data.title ?? ""),
          data.image ? String(data.image) : null,
          null,
          now,
          now
        );
      }
    }
  }
}

// Same call surface as a raw DatabaseSync (`db.prepare(...)`, `db.exec(...)`)
// so every *-db.ts data-access module needs zero changes — but the real
// connection is only opened on the first call, not on import.
const db = {
  prepare(sql: string): StatementSync {
    return getConnection().prepare(sql);
  },
  exec(sql: string): void {
    getConnection().exec(sql);
  },
};

export default db;
