import "server-only";
import { DatabaseSync, type StatementSync } from "node:sqlite";
import fs from "fs";
import path from "path";
import matter from "gray-matter";

// Defaults to <project root>/data, but this resolves relative to
// process.cwd() at runtime — which for a Next.js `output: standalone`
// deploy is `.next/standalone/`, a folder that gets fully regenerated by
// every new build. If that's how this app is hosted, dashboard-created
// content (posts, enquiries, uploads) would be wiped on every redeploy
// unless DASHBOARD_DATA_DIR is set to a path outside the build output that
// the hosting platform actually keeps between deploys.
const DATA_DIR = process.env.DASHBOARD_DATA_DIR
  ? path.resolve(process.env.DASHBOARD_DATA_DIR)
  : path.join(process.cwd(), "data");
const DB_PATH = path.join(DATA_DIR, "dashboard.db");

let instance: DatabaseSync | null = null;

// Lazy singleton — the connection (and one-time migrations below) only run
// on the first real query, not at module-import time. Next.js's build can
// run dozens of parallel workers that all import every module reachable
// from a page; if this ran at import time, they'd all fight over the same
// SQLite file during static generation and the build would fail with a
// "database locked" error. Pages that read this DB are also marked
// `export const dynamic = "force-dynamic"` so they're never statically
// generated in the first place — this lazy init is the second layer of
// defense, and also what keeps concurrent runtime requests safe.
function getConnection(): DatabaseSync {
  if (instance) return instance;

  if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });
  const conn = new DatabaseSync(DB_PATH);
  conn.exec("PRAGMA busy_timeout = 5000;");
  runMigrations(conn);
  instance = conn;
  return conn;
}

function ensureColumn(conn: DatabaseSync, table: string, column: string, ddl: string) {
  const cols = conn.prepare(`PRAGMA table_info(${table})`).all() as { name: string }[];
  if (!cols.some((c) => c.name === column)) {
    conn.exec(`ALTER TABLE ${table} ADD COLUMN ${ddl}`);
  }
}

function runMigrations(conn: DatabaseSync) {
  conn.exec(`
    CREATE TABLE IF NOT EXISTS blog_posts (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      slug TEXT UNIQUE NOT NULL,
      title TEXT NOT NULL,
      excerpt TEXT NOT NULL,
      image TEXT NOT NULL,
      team TEXT NOT NULL,
      category TEXT NOT NULL,
      date TEXT NOT NULL,
      read_time TEXT NOT NULL,
      tags TEXT NOT NULL,
      author_key TEXT NOT NULL,
      body_markdown TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'published',
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS enquiries (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      created_at TEXT NOT NULL,
      source TEXT NOT NULL,
      name TEXT,
      email TEXT,
      phone TEXT,
      subject TEXT,
      message TEXT,
      data TEXT NOT NULL,
      read INTEGER NOT NULL DEFAULT 0
    );

    CREATE TABLE IF NOT EXISTS job_openings (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      title TEXT NOT NULL,
      department TEXT NOT NULL,
      location TEXT NOT NULL,
      type TEXT NOT NULL,
      description TEXT NOT NULL,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS case_studies (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      ref TEXT UNIQUE NOT NULL,
      cat TEXT NOT NULL,
      pages TEXT NOT NULL,
      title TEXT NOT NULL,
      image TEXT,
      pdf_url TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS resources (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      ref TEXT UNIQUE NOT NULL,
      cat TEXT NOT NULL,
      format TEXT NOT NULL,
      title TEXT NOT NULL,
      image TEXT,
      pdf_url TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS projects (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      slug TEXT UNIQUE NOT NULL,
      cat TEXT NOT NULL,
      interior_category TEXT,
      digital_category TEXT,
      title TEXT NOT NULL,
      location TEXT NOT NULL,
      discipline TEXT NOT NULL,
      stage TEXT NOT NULL,
      technology TEXT NOT NULL,
      image TEXT NOT NULL,
      summary TEXT NOT NULL,
      body TEXT NOT NULL,
      scope TEXT NOT NULL,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    );
  `);

  // Existing databases created before these columns existed won't get them
  // from CREATE TABLE IF NOT EXISTS — add them explicitly, once.
  ensureColumn(conn, "blog_posts", "status", "status TEXT NOT NULL DEFAULT 'published'");
  ensureColumn(conn, "blog_posts", "publish_at", "publish_at TEXT");
  ensureColumn(conn, "enquiries", "read", "read INTEGER NOT NULL DEFAULT 0");
  ensureColumn(conn, "projects", "digital_category", "digital_category TEXT");

  // One-time migration: seed the DB from the existing markdown posts the
  // first time this ever runs, so the switchover to DB-backed content
  // doesn't lose the posts that already shipped.
  const postCount = conn.prepare("SELECT COUNT(*) as n FROM blog_posts").get() as { n: number };
  if (postCount.n === 0) {
    const contentDir = path.join(process.cwd(), "content", "insights");
    if (fs.existsSync(contentDir)) {
      const files = fs.readdirSync(contentDir).filter((f) => f.endsWith(".md"));
      const insert = conn.prepare(`
        INSERT INTO blog_posts (slug, title, excerpt, image, team, category, date, read_time, tags, author_key, body_markdown, created_at, updated_at)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `);
      const now = new Date().toISOString();
      for (const file of files) {
        const slug = file.replace(/\.md$/, "");
        const raw = fs.readFileSync(path.join(contentDir, file), "utf8");
        const { data, content } = matter(raw);
        insert.run(
          slug,
          String(data.title ?? ""),
          String(data.excerpt ?? ""),
          String(data.image ?? ""),
          String(data.team ?? ""),
          String(data.category ?? ""),
          String(data.date ?? now.slice(0, 10)),
          String(data.readTime ?? ""),
          JSON.stringify(data.tags ?? []),
          String(data.author ?? "shangeeth"),
          content.trim(),
          now,
          now
        );
      }
    }
  }

  // One-time migration: seed the one job opening that was still hardcoded in
  // the component, so switching Careers to DB-backed data doesn't drop it.
  const jobCount = conn.prepare("SELECT COUNT(*) as n FROM job_openings").get() as { n: number };
  if (jobCount.n === 0) {
    const now = new Date().toISOString();
    conn
      .prepare(
        `INSERT INTO job_openings (title, department, location, type, description, created_at, updated_at)
         VALUES (?, ?, ?, ?, ?, ?, ?)`
      )
      .run(
        "Interior Designer",
        "Design & Interiors",
        "Coimbatore / Remote",
        "Full-time",
        "Develop interior design solutions from concept through construction documentation, working closely with our BIM-integrated workflow.",
        now,
        now
      );
  }

  // One-time migration: seed case studies and resources from their existing
  // markdown content the first time this runs.
  const caseStudyCount = conn.prepare("SELECT COUNT(*) as n FROM case_studies").get() as { n: number };
  if (caseStudyCount.n === 0) {
    const dir = path.join(process.cwd(), "content", "case-studies");
    if (fs.existsSync(dir)) {
      const files = fs.readdirSync(dir).filter((f) => f.endsWith(".md"));
      const insert = conn.prepare(
        `INSERT INTO case_studies (ref, cat, pages, title, image, pdf_url, created_at, updated_at)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?)`
      );
      const now = new Date().toISOString();
      for (const file of files) {
        const raw = fs.readFileSync(path.join(dir, file), "utf8");
        const { data } = matter(raw);
        insert.run(
          String(data.ref ?? ""),
          String(data.cat ?? ""),
          String(data.pages ?? ""),
          String(data.title ?? ""),
          data.image ? String(data.image) : null,
          null,
          now,
          now
        );
      }
    }
  }

  const resourceCount = conn.prepare("SELECT COUNT(*) as n FROM resources").get() as { n: number };
  if (resourceCount.n === 0) {
    const dir = path.join(process.cwd(), "content", "resources");
    if (fs.existsSync(dir)) {
      const files = fs.readdirSync(dir).filter((f) => f.endsWith(".md"));
      const insert = conn.prepare(
        `INSERT INTO resources (ref, cat, format, title, image, pdf_url, created_at, updated_at)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?)`
      );
      const now = new Date().toISOString();
      for (const file of files) {
        const raw = fs.readFileSync(path.join(dir, file), "utf8");
        const { data } = matter(raw);
        insert.run(
          String(data.ref ?? ""),
          String(data.cat ?? ""),
          String(data.format ?? "pdf"),
          String(data.title ?? ""),
          data.image ? String(data.image) : null,
          null,
          now,
          now
        );
      }
    }
  }

  // One-time migration: seed the project portfolio ("Built Environment" and
  // "Interiors") from what used to be a hardcoded array in lib/projects.ts,
  // so switching it to dashboard-editable content doesn't lose what already
  // shipped.
  const projectCount = conn.prepare("SELECT COUNT(*) as n FROM projects").get() as { n: number };
  if (projectCount.n === 0) {
    const insert = conn.prepare(
      `INSERT INTO projects (slug, cat, interior_category, title, location, discipline, stage, technology, image, summary, body, scope, created_at, updated_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
    );
    const now = new Date().toISOString();
    const seedProjects: {
      slug: string;
      cat: string;
      interiorCategory: string | null;
      title: string;
      location: string;
      discipline: string;
      stage: string;
      technology: string[];
      image: string;
      summary: string;
      body: string[];
      scope: string[];
    }[] = [
      {
        slug: "bim-coordination-cultural-campus",
        cat: "specialized",
        interiorCategory: null,
        title: "BIM Coordination for a Mixed-Use Cultural Campus",
        location: "India",
        discipline: "BIM & VDC",
        stage: "As-Built",
        technology: ["Revit", "Navisworks", "ACC"],
        image: "/brand/projects/cultural-campus.jpg",
        summary:
          "Federated BIM coordination across architecture, structure and MEP for a multi-building cultural campus, resolving clashes before they reached the site team.",
        body: [
          "The campus brought together a performance hall, a library and an exhibition wing on a single shared podium — three design teams working to different schedules, all tying back into one structural and services grid.",
          "UCX ran federated model coordination from design development through issue-for-construction: publishing cadence across disciplines, clash detection sweeps at each milestone, and a shared coordination log so every resolved issue had a record the site team could trust.",
          "By the time drawings were issued for construction, the disciplines had already reconciled their geometry against one federated model — not three separate ones exported into the same folder.",
        ],
        scope: ["Federated BIM coordination", "Clash detection & resolution", "Multidisciplinary model management", "Coordination documentation"],
      },
      {
        slug: "hospitality-interior-design-documentation",
        cat: "specialized",
        interiorCategory: "hospitality-retail",
        title: "Interior Design & Documentation for a Hospitality Development",
        location: "UAE",
        discipline: "Design & Interiors",
        stage: "Construction",
        technology: ["Revit", "SketchUp", "ACC"],
        image: "/brand/projects/hospitality-interiors.jpg",
        summary:
          "Interior design development and construction documentation for a hospitality property, carrying concept intent through to a buildable drawing set.",
        body: [
          "The brief called for a guest experience built around material warmth and custom joinery — the kind of detail that reads well in a concept render but needs real resolution before it can go to site.",
          "UCX's interiors team worked alongside the design lead through design development, resolving material transitions, custom furniture details and services coordination, then carried that resolution into a full construction documentation set.",
          "The result was a drawing package the contractor could actually build from, without the usual second round of design decisions happening on site under deadline pressure.",
        ],
        scope: ["Interior design development", "Custom furniture detailing", "Construction documentation", "Material & finish coordination"],
      },
      {
        slug: "construction-support-medical-campus",
        cat: "specialized",
        interiorCategory: null,
        title: "Construction Support for a Regional Medical Campus",
        location: "India",
        discipline: "Construction Support",
        stage: "Construction",
        technology: ["Revit", "Navisworks", "ACC"],
        image: "/brand/projects/medical-campus.jpg",
        summary:
          "On-site aligned construction support and QA/QC coordination for a regional medical campus, keeping documentation in step with a fast-moving build.",
        body: [
          "Healthcare construction carries tighter tolerances than most sectors — services coordination in particular has almost no room for on-site improvisation once walls close in.",
          "UCX provided construction-phase support: tracking RFIs against the model, running QA/QC checks on issued drawings before they reached the contractor, and keeping the documentation set current as site conditions surfaced changes.",
          "The campus stayed on its documentation schedule through a construction phase that saw more late-stage coordination changes than the original program anticipated.",
        ],
        scope: ["Construction-phase support", "QA/QC coordination", "RFI tracking against model", "Documentation control"],
      },
      {
        slug: "asset-information-infrastructure-corridor",
        cat: "infrastructure",
        interiorCategory: null,
        title: "Asset Information Delivery for an Urban Infrastructure Corridor",
        location: "United Kingdom",
        discipline: "Asset Information",
        stage: "As-Built",
        technology: ["Revit", "COBie", "ACC"],
        image: "/brand/projects/infrastructure-corridor.jpg",
        summary:
          "Structured asset information delivery for an urban infrastructure corridor, built to the client's data requirements from day one rather than reverse-engineered at handover.",
        body: [
          "Infrastructure corridors hand over to operations teams who need structured data more than they need visual detail — asset type, install date, maintenance record linkage.",
          "UCX defined the asset information requirements early against a COBie-equivalent structure, validated it against the operator's own FM software, and delivered a dataset built to be opened, not archived.",
          "The corridor's operations team had a usable asset register from day one of handover, not a design model relabeled as a digital twin.",
        ],
        scope: ["Asset information requirements", "COBie-structured data delivery", "FM system validation", "Digital handover support"],
      },
      {
        slug: "scan-to-bim-urban-development",
        cat: "infrastructure",
        interiorCategory: null,
        title: "Scan-to-BIM for a Multi-Zone Urban Development",
        location: "United States",
        discipline: "Scan-to-BIM",
        stage: "Design",
        technology: ["Revit", "Recap", "Navisworks"],
        image: "/brand/projects/urban-development.jpg",
        summary:
          "Point-cloud-to-model translation across a multi-zone urban redevelopment, scoped to the specific decisions each zone's design team needed to make.",
        body: [
          "A multi-zone retrofit meant the scan-to-BIM scope wasn't uniform — a structural retrofit zone and an MEP re-route zone needed different things from the same underlying point cloud data.",
          "UCX defined level-of-development requirements per zone before scanning began, then modeled each zone to answer the specific questions its design team had, rather than modeling everything to a single blanket standard.",
          "That scoping decision kept the translation from as-built conditions to usable models on schedule across all zones, instead of the slowest zone setting the pace for the rest.",
        ],
        scope: ["Point cloud registration", "Scan-to-BIM modeling", "Level of development scoping", "As-built model QA"],
      },
      {
        slug: "workplace-interiors-corporate-hq",
        cat: "commercial",
        interiorCategory: "workplace-office",
        title: "Workplace Interiors for a Corporate Headquarters",
        location: "India",
        discipline: "Workplace & Office",
        stage: "Design",
        technology: ["Revit", "SketchUp", "ACC"],
        image: "/brand/projects/corporate-workplace.jpg",
        summary:
          "Workplace interior design and delivery for a corporate headquarters fit-out, balancing an open-plan brief against real services and structural constraints.",
        body: [
          "The client wanted an open, flexible floor plate across several levels of an existing shell — which meant the interiors team was designing around structural columns, existing services risers and fire compartmentation rather than a blank slate.",
          "UCX worked through design development and documentation to reconcile the workplace brief with those fixed constraints, keeping the open-plan intent intact while resolving it against what the building could actually support.",
          "The fit-out delivered the flexible workplace the brief asked for, without the compromises that usually surface only once construction starts.",
        ],
        scope: ["Workplace interior design", "Fit-out documentation", "Services & structural coordination", "Modular furniture planning"],
      },
    ];

    for (const p of seedProjects) {
      insert.run(
        p.slug,
        p.cat,
        p.interiorCategory,
        p.title,
        p.location,
        p.discipline,
        p.stage,
        JSON.stringify(p.technology),
        p.image,
        p.summary,
        JSON.stringify(p.body),
        JSON.stringify(p.scope),
        now,
        now
      );
    }
  }

  // One-time backfill: give the 3 seed projects with an obvious discipline
  // match a Digital Project Experience category, so that page isn't empty
  // right after this feature ships. Guarded on "no project has one yet" so
  // it never overwrites a category an admin has since changed.
  const digitalCatCount = conn
    .prepare("SELECT COUNT(*) as n FROM projects WHERE digital_category IS NOT NULL")
    .get() as { n: number };
  if (digitalCatCount.n === 0) {
    const backfill: [string, string][] = [
      ["bim-coordination-cultural-campus", "bim-vdc"],
      ["scan-to-bim-urban-development", "scan-to-bim"],
      ["asset-information-infrastructure-corridor", "as-built-bim"],
    ];
    const update = conn.prepare("UPDATE projects SET digital_category = ? WHERE slug = ?");
    for (const [slug, cat] of backfill) update.run(cat, slug);
  }
}

// Same call surface as a raw DatabaseSync (`db.prepare(...)`, `db.exec(...)`)
// so every *-db.ts data-access module needs zero changes — but the real
// connection is only opened on the first call, not on import.
const db = {
  prepare(sql: string): StatementSync {
    return getConnection().prepare(sql);
  },
  exec(sql: string): void {
    getConnection().exec(sql);
  },
};

export default db;
